patch=0
buildTime=0
build=0
releaseType=release
# This is a fake version number since minecraft has changed it to be <year>.<drop>.<patch>=
currentMCVersion=1.23
initialMCVersion=1.19.1
version=5.0.0
