[versions]

# Minecraft
minecraft = "26.3-rc-2"
neoform = "26.3-rc-2-1"
fabric-api = "0.160.4+26.3"
neoforge = "26.2.0.0-beta"

# Libraries
yabn = "1.0.3"
bytecodecs = "1.1.3"
resourceful-service-plugin = "1.0.0"

# Plugins
resourceful-minecraft = "2.0.0"

[libraries]

yabn = { module = "com.teamresourceful:yabn", version.ref = "yabn" }
bytecodecs = { module = "com.teamresourceful:bytecodecs", version.ref = "bytecodecs" }

service-plugin = { module = "com.teamresourceful:resourceful-service-plugin", version.ref = "resourceful-service-plugin" }

[plugins]

resourceful-minecraft = { id = "com.teamresourceful.plugins.minecraft", version.ref = "resourceful-minecraft" }
resourceful-gradle = { id = "com.teamresourceful.resourcefulgradle" }